name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  container-image:
    runs-on: ubuntu-latest
    environment:
      name: dockerhub
      url: https://hub.docker.com/layers/gidoichi/secrets-store-csi-driver-provider-infisical/${{ github.ref_name }}/images/sha256-${{ steps.sha256.outputs.digest }}
    steps:
      - uses: docker/login-action@v3
        with:
          username: gidoichi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        id: docker
        with:
          push: true
          tags: ${{ github.repository }}:${{ github.ref_name }},${{ github.repository }}:latest
      - id: sha256
        env:
          digest: ${{ steps.docker.outputs.digest }}
        run: echo "digest=${digest#sha256:}" >> "$GITHUB_OUTPUT"

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Generate Charts
        working-directory: charts
        env:
          PROVIDER_VERSION: ${{ needs.go-test.outputs.version }}
        run: |
          set -eux
          helm package secrets-store-csi-driver-provider-infisical
          for file in *.tgz; do mv {,chart-}"$file"; done
      - uses: softprops/action-gh-release@v2
        with:
          files: charts/chart-*.tgz
