name: Test
on:
  workflow_dispatch:
  push:
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          push: false

  go-test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.runtime }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: |
          set -eux
          go build -v ./...
          (cd admission-webhook && go build -v ./...)
      - name: Test
        run: |
          set -eux
          go test -v ./...
          (cd admission-webhook && go test -v ./...)
      - name: Version
        id: version
        run: |
          set -x
          printf 'runtime=%s' "$(go run main.go --version)" >> "$GITHUB_OUTPUT"

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - run: terraform init
        working-directory: github
      - run: terraform plan -detailed-exitcode -refresh=false
        working-directory: github
        env:
          TF_VAR_GITHUB_TOKEN: ""

  updated-helm-chart-index:
    runs-on: ubuntu-latest
    needs: go-test
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Diff charts/index.yaml
        working-directory: charts
        env:
          PROVIDER_VERSION: ${{ needs.go-test.outputs.version }}
        run: |
          set -eux
          helm package secrets-store-csi-driver-provider-infisical
          for file in *.tgz; do mv {,chart-}"$file"; done
          yq '.generated = null | .entries[][].digest = null | .entries[][].created = null' index.yaml > index.yaml.a
          helm repo index . --merge index.yaml --url "https://github.com/gidoichi/secrets-store-csi-driver-provider-infisical/releases/download/v${PROVIDER_VERSION}/"
          yq '.generated = null | .entries[][].digest = null | .entries[][].created = null' index.yaml > index.yaml.b

          diff index.yaml.{a,b}

  validate-helm-chart:
    runs-on: ubuntu-latest
    needs: go-test
    steps:
      - uses: actions/checkout@v4
      - name: Match provider version
        uses: mikefarah/yq@v4.44.3
        env:
          PROVIDER_VERSION: ${{ needs.go-test.outputs.version }}
        with:
          cmd: |
            file="charts/secrets-store-csi-driver-provider-infisical/Chart.yaml"
            diff <(yq --prettyPrint "$file") <(yq --prettyPrint '.appVersion = strenv(PROVIDER_VERSION)' "$file") >&2

  validate-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0
      - name: Update kuberenetes manifest
        run: |
          diff \
              deployment/infisical-csi-provider.yaml \
              <(helm template --namespace kube-system --skip-tests secrets-store-csi-driver-provider-infisical charts/secrets-store-csi-driver-provider-infisical | grep -v -e '^ *helm\.sh/chart: ' -e '^ *app.kubernetes.io/managed-by: Helm$' -e '^# Source: ') \
              >&2
